version: '3.7'

services:
  mongodb-Cont:
    image: mongo:latest 
    container_name: mongo_db_cont
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_ROOT_DATABASE: db1
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_cont:/data/db

volumes:
  mongodb_data_cont: